version: 2

python:
  version: 3.12
  install:
    - method: pip
      path: .
    - requirements: docs/requirements_doc.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py
