# Generated by Django 3.2.7 on 2021-10-05 08:08

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='goods.catalog')),
            ],
            options={
                'verbose_name': 'Catalog',
                'verbose_name_plural': 'Catalogs',
            },
        ),
        migrations.CreateModel(
            name='DosagePacking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=250, verbose_name='Quantity')),
            ],
            options={
                'verbose_name': 'Dosage packing',
                'verbose_name_plural': 'Dosage packings',
            },
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('slug', models.SlugField(editable=False, verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Maker',
                'verbose_name_plural': 'Makers',
            },
        ),
        migrations.CreateModel(
            name='OriginalPacking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=250, verbose_name='Quantity')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Original Packing',
                'verbose_name_plural': 'Original Packings',
            },
        ),
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('slug', models.SlugField(editable=False, verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Packing type',
                'verbose_name_plural': 'Packing types',
            },
        ),
        migrations.CreateModel(
            name='PharmProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, verbose_name='slug')),
                ('full_name', models.CharField(blank=True, editable=False, max_length=300, verbose_name='Full name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.catalog', verbose_name='Catalog')),
                ('dosage_packing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.dosagepacking', verbose_name='Dosage packing')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.maker', verbose_name='Maker')),
                ('original_packing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.originalpacking', verbose_name='Original packing')),
            ],
            options={
                'verbose_name': 'Pharmaceutical product',
                'verbose_name_plural': 'Pharmaceutical products',
            },
        ),
        migrations.CreateModel(
            name='TradeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('slug', models.SlugField(editable=False, verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Trade name',
                'verbose_name_plural': 'Trade names',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('slug', models.SlugField(editable=False, verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Unit of measurement',
                'verbose_name_plural': 'Units of measurement',
            },
        ),
        migrations.CreateModel(
            name='PharmProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', sorl.thumbnail.fields.ImageField(upload_to='thumbnails', verbose_name='Image')),
                ('product_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.pharmproduct', verbose_name='Parent')),
            ],
        ),
        migrations.AddField(
            model_name='pharmproduct',
            name='trade_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.tradename', verbose_name='Trade name'),
        ),
        migrations.AddField(
            model_name='originalpacking',
            name='packing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.packing', verbose_name='Packing type'),
        ),
        migrations.AddField(
            model_name='originalpacking',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.unit', verbose_name='Unit of measurement'),
        ),
        migrations.AddField(
            model_name='dosagepacking',
            name='packing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.packing', verbose_name='Packing type'),
        ),
        migrations.AddField(
            model_name='dosagepacking',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.unit', verbose_name='Unit of measurement'),
        ),
        migrations.AlterUniqueTogether(
            name='pharmproduct',
            unique_together={('trade_name', 'maker', 'dosage_packing')},
        ),
        migrations.AlterUniqueTogether(
            name='dosagepacking',
            unique_together={('packing', 'quantity', 'unit')},
        ),
    ]
