# Generated by Django 3.2.8 on 2022-07-26 06:39

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='goods.catalog')),
            ],
            options={
                'verbose_name': 'Catalog',
                'verbose_name_plural': 'Catalogs',
            },
        ),
        migrations.CreateModel(
            name='DosagePacking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Dosage packing',
                'verbose_name_plural': 'Dosage packings',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, verbose_name='slug')),
                ('full_name', models.CharField(blank=True, editable=False, max_length=300, verbose_name='Full name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.catalog', verbose_name='Catalog')),
                ('dosage_packing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.dosagepacking', verbose_name='Dosage packing')),
            ],
            options={
                'verbose_name': 'Pharmaceutical good',
                'verbose_name_plural': 'Pharmaceutical goods',
            },
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(editable=False, max_length=250, verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Maker',
                'verbose_name_plural': 'Makers',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(editable=False, max_length=250, verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Packing type',
                'verbose_name_plural': 'Packing types',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='TradeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(editable=False, max_length=250, verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Trade name',
                'verbose_name_plural': 'Trade names',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(editable=False, max_length=250, verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Unit of measurement',
                'verbose_name_plural': 'Units of measurement',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='OriginalPacking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('packing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.packing', verbose_name='Packing type')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.unit', verbose_name='Unit of measurement')),
            ],
            options={
                'verbose_name': 'Original Packing',
                'verbose_name_plural': 'Original Packings',
                'unique_together': {('packing', 'quantity', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='GoodImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='thumbnails', verbose_name='Image')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.good', verbose_name='Parent')),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.maker', verbose_name='Maker'),
        ),
        migrations.AddField(
            model_name='good',
            name='original_packing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.originalpacking', verbose_name='Original packing'),
        ),
        migrations.AddField(
            model_name='good',
            name='trade_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.tradename', verbose_name='Trade name'),
        ),
        migrations.AddField(
            model_name='dosagepacking',
            name='packing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.packing', verbose_name='Packing type'),
        ),
        migrations.AddField(
            model_name='dosagepacking',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.unit', verbose_name='Unit of measurement'),
        ),
        migrations.AlterUniqueTogether(
            name='good',
            unique_together={('trade_name', 'maker', 'original_packing', 'dosage_packing')},
        ),
        migrations.AlterUniqueTogether(
            name='dosagepacking',
            unique_together={('packing', 'quantity', 'unit')},
        ),
    ]
