# Generated by Django 5.1.11 on 2025-06-22 13:17

import django.db.models.deletion
import mptt.fields
import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name': 'Каталог', 'verbose_name_plural': 'Каталоги'},
        ),
        migrations.AlterModelOptions(
            name='dosagepacking',
            options={'verbose_name': 'Дозировка упаковки', 'verbose_name_plural': 'Дозировки упаковок'},
        ),
        migrations.AlterModelOptions(
            name='good',
            options={'verbose_name': 'Фармацевтический товар', 'verbose_name_plural': 'Фармацевтические товары'},
        ),
        migrations.AlterModelOptions(
            name='maker',
            options={'ordering': ['-name'], 'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='originalpacking',
            options={'verbose_name': 'Оригинальная упаковка', 'verbose_name_plural': 'Оригинальные упаковки'},
        ),
        migrations.AlterModelOptions(
            name='packing',
            options={'ordering': ['-name'], 'verbose_name': 'Тип упаковки', 'verbose_name_plural': 'Типы упаковок'},
        ),
        migrations.AlterModelOptions(
            name='tradename',
            options={'ordering': ['-name'], 'verbose_name': 'Торговое название', 'verbose_name_plural': 'Торговые названия'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['-name'], 'verbose_name': 'Единица измерения', 'verbose_name_plural': 'Единицы измерения'},
        ),
        migrations.AlterField(
            model_name='catalog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='дети', to='goods.catalog'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='dosagepacking',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='dosagepacking',
            name='packing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.packing', verbose_name='Тип упаковки'),
        ),
        migrations.AlterField(
            model_name='dosagepacking',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='dosagepacking',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.unit', verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='dosagepacking',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='good',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='good',
            name='dosage_packing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.dosagepacking', verbose_name='Дозировка упаковки'),
        ),
        migrations.AlterField(
            model_name='good',
            name='full_name',
            field=models.CharField(blank=True, editable=False, max_length=300, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='good',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.maker', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='good',
            name='original_packing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.originalpacking', verbose_name='Оригинальная упаковка'),
        ),
        migrations.AlterField(
            model_name='good',
            name='trade_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.tradename', verbose_name='Торговое название'),
        ),
        migrations.AlterField(
            model_name='good',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='goodimage',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.good', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='goodimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='thumbnails', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='originalpacking',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='originalpacking',
            name='packing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.packing', verbose_name='Тип упаковки'),
        ),
        migrations.AlterField(
            model_name='originalpacking',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='originalpacking',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.unit', verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='originalpacking',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='packing',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='packing',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='packing',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='tradename',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='tradename',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tradename',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
    ]
