# Generated by Django 3.2.7 on 2021-10-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=250, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='dosagepacking',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=250, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='dosagepacking',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='originalpacking',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity'),
        ),
    ]
