# Generated by Django 3.2.7 on 2021-10-08 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20211008_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosagepacking',
            name='packing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.packing', verbose_name='Packing type'),
        ),
        migrations.AlterField(
            model_name='dosagepacking',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.unit', verbose_name='Unit of measurement'),
        ),
        migrations.AlterField(
            model_name='originalpacking',
            name='packing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.packing', verbose_name='Packing type'),
        ),
        migrations.AlterField(
            model_name='originalpacking',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.unit', verbose_name='Unit of measurement'),
        ),
        migrations.AlterField(
            model_name='pharmproduct',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.catalog', verbose_name='Catalog'),
        ),
        migrations.AlterField(
            model_name='pharmproduct',
            name='dosage_packing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.dosagepacking', verbose_name='Dosage packing'),
        ),
        migrations.AlterField(
            model_name='pharmproduct',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.maker', verbose_name='Maker'),
        ),
        migrations.AlterField(
            model_name='pharmproduct',
            name='original_packing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.originalpacking', verbose_name='Original packing'),
        ),
        migrations.AlterField(
            model_name='pharmproduct',
            name='trade_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.tradename', verbose_name='Trade name'),
        ),
    ]
