# Generated by Django 3.2.7 on 2021-10-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20211008_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradename',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Name'),
        ),
    ]
