# Generated by Django 3.2.7 on 2021-10-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20211012_0812'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pharmproduct',
            unique_together={('trade_name', 'maker', 'original_packing', 'dosage_packing')},
        ),
    ]
