# Generated by Django 3.2.8 on 2022-07-08 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_alter_pharmproduct_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maker',
            options={'ordering': ['-name'], 'verbose_name': 'Maker', 'verbose_name_plural': 'Makers'},
        ),
        migrations.AlterModelOptions(
            name='packing',
            options={'ordering': ['-name'], 'verbose_name': 'Packing type', 'verbose_name_plural': 'Packing types'},
        ),
        migrations.AlterModelOptions(
            name='tradename',
            options={'ordering': ['-name'], 'verbose_name': 'Trade name', 'verbose_name_plural': 'Trade names'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['-name'], 'verbose_name': 'Unit of measurement', 'verbose_name_plural': 'Units of measurement'},
        ),
        migrations.AlterField(
            model_name='maker',
            name='slug',
            field=models.SlugField(editable=False, max_length=250, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='packing',
            name='slug',
            field=models.SlugField(editable=False, max_length=250, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='pharmproduct',
            name='dosage_packing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.dosagepacking', verbose_name='Dosage packing'),
        ),
        migrations.AlterField(
            model_name='tradename',
            name='slug',
            field=models.SlugField(editable=False, max_length=250, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='slug',
            field=models.SlugField(editable=False, max_length=250, verbose_name='slug'),
        ),
    ]
