# Generated by Django 3.2.8 on 2022-07-26 05:33

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20220709_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='thumbnails', verbose_name='Image')),
            ],
        ),
        migrations.AlterModelOptions(
            name='good',
            options={'verbose_name': 'Pharmaceutical good', 'verbose_name_plural': 'Pharmaceutical goods'},
        ),
        migrations.RenameModel(
            old_name='PharmProduct',
            new_name='Good',
        ),
        migrations.DeleteModel(
            name='PharmProductImage',
        ),
        migrations.AddField(
            model_name='goodimage',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.good', verbose_name='Parent'),
        ),
    ]
